### ISSUE TITLE
Integration with Autogen and CrewAI for structuring the outputs of agents[FEAT]

### ISSUE THREAD

**Issue by vvkishere** [firattamur/llmdantic#4]
**Is your feature request related to a problem? Please describe.**
The tool is fantastic but it would be great to integrate its functionality with Agent frameworks like CrewAI or Autogen to control the outputs of the agents within the framework. This could potentially be game changing.

**Describe the solution you'd like**
Autogen and CrewAI allow you to create tools specific to an agent. We should be able to easily create an agent tool to check on outputs and ensure consistency of the agent in getting it's tasks done. 

**Describe alternatives you've considered**
Currently my attempts are to use pydantic structures to achieve this but it doesn't seem to work well.

**Comment by firattamur** [comment]
Thank you for your feedback and the positive remarks about our tool. The idea of integrating it with agent frameworks like CrewAI or Autogen is truly intriguing and forward-thinking. At the moment, my experience with these particular tools is somewhat limited. Nevertheless, I'm open to exploring them further and potentially devising a suitable approach for integration. If there's a starting point or a basic framework available from your end, I would be more than willing to contribute my insights and collaborate on enhancing the capabilities of our tool together.

**Comment by vvkishere** [comment]
Hi. Thanks for replying.

https://github.com/joaomdmoura/crewAI : We can start with this framework. The documentation is available at : https://docs.crewai.com/

I am particularly interested in using the tools section of for the agents: https://docs.crewai.com/core-concepts/Tools/

Currently, these agents get what ever structure for their outputs from what the LLM decides at the moment. This kind of random output makes deploying these things into production very difficult. 

If we can while creating the tasks itself, define how we want to LLM to output the strucutre and check it. If it does not conform to the structure then restructure it and give out the final output in a predictable manner, these tools will become immensely more usable.

Let me know what you think.
